#+TITLE: 使用 Beancount 进行交易
#+DATE: [2020-04-22 周三]
#+AUTHOR: Martin Blais

* 简介
本文档是《命令行会计食谱》的配套文档，专门介绍了 Beancount 中的交易和投资主题。在阅读本文档之前，你可能应该先读过复式记账法的介绍。

说到股票交易这个话题，需要先讨论一下“盈亏”，也叫资本收益或损失，简称 P/L。对于新手来说，P/L 这个概念对多次交易的盈亏的概念是很难理解的，我甚至看到过专业的交易员在不同的时间段内对 P/L 的理解有所不同。这一点是值得花时间来解释的，而且有必要了解如何在复式记账系统中对交易进行预定。

本讨论将结合如何在 Beancount 中预订这些交易的详细示例进行讨论。有一个相关的、积极的改进 Beancount 预订方法的建议，您可能也会感兴趣。这里不讨论递延税项的基础，而是在更一般的食谱中讨论。

* 什么是盈亏？
假设你在 E*Trade 折扣经纪公司有一个账户，你买了一些公司的股票，比如说 IBM。如果你买入 10 股 IBM 公司的股票，当它的价格是每股 160 元时，你将花费 1600 元。这个价值就是我们所说的 "账面价值"，或者说是 "成本"。这就是你得花多少钱才能买到的股票，也叫 "仓位"。这就是你在 Beancount 中输入这个交易的方式。

#+BEGIN_SRC beancount
2014-02-16 * "Buying some IBM"
  Assets:US:ETrade:IBM                 10 IBM {160.00 USD}
  Assets:US:ETrade:Cash          -1600.00 USD
#+END_SRC

在实际操作中，你可能会向 E*Trade 支付一定的佣金来做这项服务，所以为了完整，我们把这一点放进去。

#+BEGIN_SRC beancount
2014-02-16 * "Buying some IBM"
  Assets:US:ETrade:IBM                 10 IBM {160.00 USD}
  Assets:US:ETrade:Cash          -1609.95 USD
  Expenses:Financial:Commissions     9.95 USD
#+END_SRC

这样就可以告诉 Beancount "按成本价"存入一些单位，在本例中，"IBM 以每股 160 美元的成本价"存入单位。这笔交易之所以能够平衡，因为它的分支总和为 0。10 x 160 + -1609.95 + 9.95 = 0。另外要注意的是，我们选择使用一个专门用于 IBM 的股票的子账户；这并不是严格意义上的必要，但在资产负债表中报告时很方便，因为它将自然而然地将你的每一个仓位的所有股票汇总到自己的线上。拥有一个 "现金 "子账户也强调了你在那里的未投资资金不会提供任何回报。

第二天开盘，IBM 的股价为每股 170 元。在这种情况下，我们将称之为"价格"，你的仓位的"市值"，也就是你的股票的数量 × 市价，即 10 股 × 每股 170 元 = 1700 元。

这两个数额之间的区别，就是我们所说的 P/L。

市值 - 账面价值 = P/L

10 × 170 元 - 10 × 160 元 = 1700 元 - 1600 元 = 100 元(利润)

我们将把正数称为 “利润”，如果是负数，则称为 “亏损”。
